// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvxrghjleaaasueblxpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2eHJnaGpsZWFhYXN1ZWJseHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzI4MTUsImV4cCI6MjA3MjU0ODgxNX0.Vrbxu9BPzKx1neOmcCFC9q7rqmVhdbBhalrK5wT0v9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});